import React, { useContext } from 'react';

import twitter from '../assets/twitter.png';
import discord from '../assets/discord.png';

import { Header, ProgressContainer, ProgressLabel, Sublabel, ContentCats } from '../styles/Roadmap.styles'
import { Image, SocialMediaGroup} from '../styles/Home.styles'
import ConnectionContext from '../context/connection/context';
import iconscats from '../assets/iconcats.svg'


import cat1 from '../assets/1.svg'
import cat2 from '../assets/2.svg'
import cat3 from '../assets/3.svg'
import cat4 from '../assets/4.svg'
import cat5 from '../assets/5.svg'
import cat6 from '../assets/6.svg'
import cat7 from '../assets/7.svg'
import cat8 from '../assets/8.svg'
import cat9 from '../assets/9.svg'
import groupcats from '../assets/groupcats.svg'
import { Cat } from '../styles/Genesis.styles';

const Roadmap = () => {
    const { redirectTwitter, redirectDiscord } = useContext(ConnectionContext);
    const cats = [
        {
            img: cat1
        },
        {
            img: cat2
        },
        {
            img: cat3
        },
        {
            img: cat4
        },
        {
            img: cat5
        },
        {
            img: cat6
        },
        {
            img: cat7
        },
        {
            img: cat8
        },
        {
            img: cat9
        }
    ]
    return (
        <div>
            <Header>ROADMAP</Header>
            <br />
            <Sublabel>
                Cryptonia Kittens is a collection of 10’000 generative and interactive NFTs, which are generated by code with 50 Genesis unique Kittens.
                A collection of NTFs that allows you to interact with your Cryptonia Kitten.
                The development of this collection has required the collaboration of the founders and engineers for several months to be able to offer the whole NFT-loving community this innovative product.
            </Sublabel>

            <ProgressContainer>
                <ProgressLabel width='22%'><img src={iconscats} alt="" />  April 2021</ProgressLabel>
                <ProgressLabel left='30px'>Idea, design and first draft</ProgressLabel>
            </ProgressContainer>

            <ProgressContainer>
                <ProgressLabel width='22%'><img src={iconscats} alt=""/>  May 2021</ProgressLabel>

                <ProgressLabel left='30px'>Viability and realization</ProgressLabel>
            </ProgressContainer>

            <ProgressContainer>
                <ProgressLabel width='22%'><img src={iconscats} alt=""/>  June 2021</ProgressLabel>

                <ProgressLabel left='30px'>Search for investors</ProgressLabel>
            </ProgressContainer>

            <ProgressContainer>
                <ProgressLabel width='22%'><img src={iconscats} alt=""/>  July 2021</ProgressLabel>

                <ProgressLabel left='30px'>Interactions Development</ProgressLabel>
            </ProgressContainer>

            <ProgressContainer>
                <ProgressLabel width='22%'><img src={iconscats} alt=""/>  August 2021</ProgressLabel>

                <ProgressLabel left='30px'>Development, programming and testing</ProgressLabel>
            </ProgressContainer>



            <ProgressContainer>
                <ProgressLabel width='22%'><img src={iconscats} alt="" />  September 2021</ProgressLabel>

                <ProgressLabel left='30px'>Implementation of the Cryptonia Kittens</ProgressLabel>
            </ProgressContainer>

            <ProgressContainer>
                <ProgressLabel width='22%'><img src={iconscats} alt=""/>  September 2021</ProgressLabel>

                <ProgressLabel left='30px'>Registration of protocols and tokens on the blockchain</ProgressLabel>
            </ProgressContainer>

            <ProgressContainer>
                <ProgressLabel width='22%'><img src={iconscats} alt=""/>  December 2021</ProgressLabel>

                <ProgressLabel left='30px'>Cryptonia Kittens are online</ProgressLabel>
            </ProgressContainer>

            <ProgressContainer>
                <ProgressLabel width='22%'><img src={iconscats} alt=""/>2022</ProgressLabel>
                <ProgressLabel left='30px'>
                    Going live to Decentraland, Cryptonia Kitten’s
                    holders will gain access to THE CLUB
                </ProgressLabel>
            </ProgressContainer>

            <h1 style={{ color: '#FED144', textAlign: 'center', marginTop: '50px' }}>More exciting features coming soon in 2022</h1>

            <ContentCats style={{ marginTop: '50px' }}>
                {cats.map((cat, key) => (
                    <Cat width='50px' key={key} src={cat.img} />
                ))}
            </ContentCats>
            <ContentCats style={{ marginTop: '50px' }} width='100%'>
                <Cat width='100%' src={groupcats} />
            </ContentCats>


            <SocialMediaGroup>
                <Image onClick={redirectTwitter} src={twitter} />
                <Image onClick={redirectDiscord} src={discord} />
            </SocialMediaGroup>
        </div>
    )
}

export default Roadmap;